# Generated by Django 5.0.7 on 2024-08-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
