# Generated by Django 5.0.7 on 2024-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
